/**
 * Supabase Client for Frontend
 * Uses anon/publishable key for RLS-protected operations
 */

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables. Check your .env.local file.');
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});

// Type-safe database schema (auto-generated by Prisma)
export type Database = {
  public: {
    Tables: {
      clientes: {
        Row: {
          id: string;
          nombre: string;
          codigo: string;
          fecha_creacion: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['clientes']['Row'], 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['clientes']['Insert']>;
      };
      proyectos: {
        Row: {
          id: string;
          cliente_id: string;
          nombre: string;
          estado: 'Pendiente' | 'En Proceso' | 'Completado';
          fecha_inicio: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['proyectos']['Row'], 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['proyectos']['Insert']>;
      };
      // Add more table types as needed
    };
  };
};
